// <auto-generated />
using ExoticIslands_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExoticIslands_api.Data.Migrations
{
    [DbContext(typeof(IslandContext))]
    [Migration("20241105041258_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ExoticIslands_api.Models.Island", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base64Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Islands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base64Image = "",
                            Country = "French Polynesia",
                            Description = "Famous for its seaside luxury resorts, turquoise lagoons, and coral reefs.",
                            Name = "Bora Bora"
                        },
                        new
                        {
                            Id = 2,
                            Base64Image = "",
                            Country = "Maldives",
                            Description = "The maldives is a country that is filled with a series of 1,192 different exotic islands.",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 3,
                            Base64Image = "",
                            Country = "French Polynesia",
                            Description = "Tahiti is the largest island in French Polunesia. It has a shape of a figure-8 when viewed from above.",
                            Name = "Tahiti"
                        },
                        new
                        {
                            Id = 4,
                            Base64Image = "",
                            Country = "Seychelles",
                            Description = "The seychelles is the smallest country in Africa and holds a number of 115 islands in the Indian Ocean.",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 5,
                            Base64Image = "",
                            Country = "Philippines",
                            Description = "Palawan is an archipelagic province located in the region of Mimaropa.",
                            Name = "Palawan"
                        },
                        new
                        {
                            Id = 6,
                            Base64Image = "",
                            Country = "Indonesia",
                            Description = "Bali is a province of Indonesia and the westernmost of the Lesser Sunda Islands.",
                            Name = "Bali"
                        },
                        new
                        {
                            Id = 7,
                            Base64Image = "",
                            Country = "United States",
                            Description = "Hawaii is an island state in the Pacific Ocean, the only US state in the tropics.",
                            Name = "Hawaii"
                        },
                        new
                        {
                            Id = 8,
                            Base64Image = "",
                            Country = "Saint Kitts and Nevis",
                            Description = "An island country consisting of the two islands of Saint Kitts and Nevis.",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 9,
                            Base64Image = "",
                            Country = "Thailand",
                            Description = "Phi Phi Islands are an island group in Thailand between the large island of Phuket and Straits of Malacca coast of Thailand.",
                            Name = "Ko Phi Phi"
                        },
                        new
                        {
                            Id = 10,
                            Base64Image = "",
                            Country = "Ecuador",
                            Description = "The Galapagos Islands is a volcanic archipelago and also considered one of the world's foremost destinations for wildlife-viewing.",
                            Name = "Galapagos Islands"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
