// <auto-generated />
using ExoticIslands_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExoticIslands_api.Data.Migrations
{
    [DbContext(typeof(IslandContext))]
    [Migration("20241104194326_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ExoticIslands_api.Models.Island", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base64Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Islands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base64Image = "",
                            Country = "French Polynesia",
                            Description = "Famous for its seaside luxury resorts, turquoise lagoons, and coral reefs.",
                            Name = "Bora Bora"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
